monitor = eDP-1, 1920x1080@60, 0x0, 1
monitor = HDMI-A-1, 1920x1080@144, 1920x0, 1

# -----------------------------------------------------
# Performance & Battery Optimization
# -----------------------------------------------------

decoration {
    rounding = 0             # Minimal rounding takes less rendering power
#    drop_shadow = false      # Shadow rendering eats GPU cycles
    
    blur {
        enabled = false      # CRITICAL: Blur is the #1 battery killer
    }
}

animations {
    enabled = true

    # Snappy Bezier curve (fast acceleration, quick finish)
    bezier = snap, 0.03, 0.6, 0.03, 0.6

    # Animation settings: (Instance, Enabled, Speed (100ms units), Curve, Style)
    # Keeping speed numbers low (2-4) means animations finish in a flash, saving power.
    animation = windows, 1, 2, snap, slide
    animation = windowsOut, 1, 2, snap, slide
    animation = border, 1, 2, default               # Disabled: borders don't need to fade
    animation = borderangle, 1, 2, default          # Disabled: rotating borders drain battery
    animation = fade, 1, 2, snap
    animation = workspaces, 1, 2, snap, slidefade 5%
}

misc {
 #   vfr = true               # Variable Frame Rate: Dropping FPS to 0 when nothing moves saves massive power
    vrr = 1                  # Variable Refresh Rate (Adaptive Sync): 0 = off, 1 = on, 2 = fullscreen only
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

# Apps And Keybinds
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$mainMod = SUPER
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, F, fullscreen, 1
bind = $mainMod, D, exec, $menu
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-



# AUTO START
exec-once = waybar
exec-once = swaybg -i Downloads/512679.jpg 
exec-once = python hyprdock2.py
